- pkg:deb/debian/prometheus@2.24.1%2Bds-1%2Bb7?arch=amd64
- pkg:deb/debian/prometheus@2.24.1%2Bds-1%2Bb7?arch=arm64
- pkg:deb/debian/prometheus@2.24.1%2Bds-1%2Bb7?arch=armhf
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=amd64
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=arm64
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=armel
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=armhf
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=i386
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=mips64el
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=mipsel
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=ppc64el
- pkg:deb/debian/prometheus@2.42.0%2Bds-5%2Bb6?arch=s390x
- pkg:deb/debian/prometheus@2.53.3%2Bds1-2?arch=amd64
- pkg:deb/debian/prometheus@2.53.3%2Bds1-2?arch=arm64
- pkg:deb/debian/prometheus@2.53.3%2Bds1-2?arch=armel
- pkg:deb/debian/prometheus@2.53.3%2Bds1-2?arch=armhf
- pkg:deb/debian/prometheus@2.53.3%2Bds1-2?arch=i386
- pkg:deb/debian/prometheus@2.53.3%2Bds1-2?arch=ppc64el
- pkg:deb/debian/prometheus@2.53.3%2Bds1-2?arch=riscv64
- pkg:deb/debian/prometheus@2.53.3%2Bds1-2?arch=s390x
- pkg:deb/debian/prometheus@2.53.5%2Bds1-2?arch=amd64
- pkg:deb/debian/prometheus@2.53.5%2Bds1-2?arch=arm64
- pkg:deb/debian/prometheus@2.53.5%2Bds1-2?arch=armhf
- pkg:deb/debian/prometheus@2.53.5%2Bds1-2?arch=i386
- pkg:deb/debian/prometheus@2.53.5%2Bds1-2?arch=ppc64el
- pkg:deb/debian/prometheus@2.53.5%2Bds1-2?arch=riscv64
- pkg:deb/debian/prometheus@2.53.5%2Bds1-2?arch=s390x
