- pkg:deb/debian/librust-prometheus-dev@0.13.3-1?arch=amd64
- pkg:deb/debian/librust-prometheus-dev@0.13.3-1?arch=arm64
- pkg:deb/debian/librust-prometheus-dev@0.13.3-1?arch=armhf
- pkg:deb/debian/librust-prometheus-dev@0.13.3-1?arch=i386
- pkg:deb/debian/librust-prometheus-dev@0.13.3-1?arch=mips64el
- pkg:deb/debian/librust-prometheus-dev@0.13.3-1?arch=ppc64el
- pkg:deb/debian/librust-prometheus-dev@0.13.3-1?arch=s390x
- pkg:deb/debian/librust-prometheus-dev@0.13.4-4?arch=amd64
- pkg:deb/debian/librust-prometheus-dev@0.13.4-4?arch=arm64
- pkg:deb/debian/librust-prometheus-dev@0.13.4-4?arch=armhf
- pkg:deb/debian/librust-prometheus-dev@0.13.4-4?arch=i386
- pkg:deb/debian/librust-prometheus-dev@0.13.4-4?arch=ppc64el
- pkg:deb/debian/librust-prometheus-dev@0.13.4-4?arch=riscv64
- pkg:deb/debian/librust-prometheus-dev@0.13.4-4?arch=s390x
- pkg:deb/debian/librust-prometheus-dev@0.13.4-5?arch=amd64
- pkg:deb/debian/librust-prometheus-dev@0.13.4-5?arch=arm64
- pkg:deb/debian/librust-prometheus-dev@0.13.4-5?arch=armhf
- pkg:deb/debian/librust-prometheus-dev@0.13.4-5?arch=i386
- pkg:deb/debian/librust-prometheus-dev@0.13.4-5?arch=ppc64el
- pkg:deb/debian/librust-prometheus-dev@0.13.4-5?arch=riscv64
- pkg:deb/debian/librust-prometheus-dev@0.13.4-5?arch=s390x
