- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=armel
- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=i386
- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=mips64el
- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=mipsel
- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=ppc64el
- pkg:deb/debian/prometheus-postgres-exporter@0.11.1-3%2Bb5?arch=s390x
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb4?arch=amd64
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb4?arch=arm64
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb4?arch=armel
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb4?arch=armhf
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb4?arch=i386
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb4?arch=ppc64el
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb4?arch=riscv64
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb4?arch=s390x
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb5?arch=i386
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb5?arch=ppc64el
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb5?arch=riscv64
- pkg:deb/debian/prometheus-postgres-exporter@0.17.1-1%2Bb5?arch=s390x
- pkg:deb/debian/prometheus-postgres-exporter@0.8.0%2Bds-1%2Bb6?arch=amd64
- pkg:deb/debian/prometheus-postgres-exporter@0.8.0%2Bds-1%2Bb6?arch=arm64
- pkg:deb/debian/prometheus-postgres-exporter@0.8.0%2Bds-1%2Bb6?arch=armhf
- pkg:deb/debian/prometheus-postgres-exporter@0.8.0%2Bds-1%2Bb6?arch=i386
