- pkg:deb/debian/prometheus-node-exporter@1.1.2%2Bds-2.1?arch=amd64
- pkg:deb/debian/prometheus-node-exporter@1.1.2%2Bds-2.1?arch=arm64
- pkg:deb/debian/prometheus-node-exporter@1.1.2%2Bds-2.1?arch=armhf
- pkg:deb/debian/prometheus-node-exporter@1.1.2%2Bds-2.1?arch=i386
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=amd64
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=arm64
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=armel
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=armhf
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=i386
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=mips64el
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=mipsel
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=ppc64el
- pkg:deb/debian/prometheus-node-exporter@1.5.0-1%2Bb6?arch=s390x
- pkg:deb/debian/prometheus-node-exporter@1.9.0-1%2Bb4?arch=amd64
- pkg:deb/debian/prometheus-node-exporter@1.9.0-1%2Bb4?arch=arm64
- pkg:deb/debian/prometheus-node-exporter@1.9.0-1%2Bb4?arch=armel
- pkg:deb/debian/prometheus-node-exporter@1.9.0-1%2Bb4?arch=armhf
- pkg:deb/debian/prometheus-node-exporter@1.9.0-1%2Bb4?arch=i386
- pkg:deb/debian/prometheus-node-exporter@1.9.0-1%2Bb4?arch=ppc64el
- pkg:deb/debian/prometheus-node-exporter@1.9.0-1%2Bb4?arch=riscv64
- pkg:deb/debian/prometheus-node-exporter@1.9.0-1%2Bb4?arch=s390x
- pkg:deb/debian/prometheus-node-exporter@1.9.1-1?arch=amd64
- pkg:deb/debian/prometheus-node-exporter@1.9.1-1?arch=arm64
- pkg:deb/debian/prometheus-node-exporter@1.9.1-1?arch=armhf
- pkg:deb/debian/prometheus-node-exporter@1.9.1-1?arch=i386
- pkg:deb/debian/prometheus-node-exporter@1.9.1-1?arch=ppc64el
- pkg:deb/debian/prometheus-node-exporter@1.9.1-1?arch=riscv64
- pkg:deb/debian/prometheus-node-exporter@1.9.1-1?arch=s390x
