- pkg:deb/debian/prometheus-bind-exporter@0.4.0%2Bds-1%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-bind-exporter@0.4.0%2Bds-1%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-bind-exporter@0.4.0%2Bds-1%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-bind-exporter@0.4.0%2Bds-1%2Bb5?arch=i386
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=amd64
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=arm64
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=armel
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=armhf
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=i386
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=mips64el
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=mipsel
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=ppc64el
- pkg:deb/debian/prometheus-bind-exporter@0.6.1-1%2Bb1?arch=s390x
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb6?arch=amd64
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb6?arch=arm64
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb6?arch=armel
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb6?arch=armhf
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb6?arch=i386
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb6?arch=ppc64el
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb6?arch=riscv64
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb6?arch=s390x
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb7?arch=amd64
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb7?arch=arm64
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb7?arch=armhf
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb7?arch=i386
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb7?arch=ppc64el
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb7?arch=riscv64
- pkg:deb/debian/prometheus-bind-exporter@0.8.0-1%2Bb7?arch=s390x
