- pkg:deb/debian/prometheus-hacluster-exporter@1.2.1-1%2Bb6?arch=amd64
- pkg:deb/debian/prometheus-hacluster-exporter@1.2.1-1%2Bb6?arch=arm64
- pkg:deb/debian/prometheus-hacluster-exporter@1.2.1-1%2Bb6?arch=armhf
- pkg:deb/debian/prometheus-hacluster-exporter@1.2.1-1%2Bb6?arch=i386
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=amd64
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=arm64
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=armel
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=armhf
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=i386
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=mips64el
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=mipsel
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=ppc64el
- pkg:deb/debian/prometheus-hacluster-exporter@1.3.1-1%2Bb3?arch=s390x
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb5?arch=armel
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb5?arch=i386
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb5?arch=ppc64el
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb5?arch=riscv64
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb5?arch=s390x
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb6?arch=amd64
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb6?arch=arm64
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb6?arch=armhf
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb6?arch=i386
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb6?arch=ppc64el
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb6?arch=riscv64
- pkg:deb/debian/prometheus-hacluster-exporter@1.4.0-1%2Bb6?arch=s390x
