- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=amd64
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=arm64
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=armel
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=armhf
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=i386
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=mips64el
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=mipsel
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=ppc64el
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb14?arch=s390x
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb7?arch=amd64
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb7?arch=arm64
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb7?arch=armhf
- pkg:deb/debian/prometheus-exporter-exporter@0.4.0-1%2Bb7?arch=i386
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb3?arch=amd64
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb3?arch=arm64
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb3?arch=armel
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb3?arch=armhf
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb3?arch=i386
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb3?arch=ppc64el
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb3?arch=riscv64
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb3?arch=s390x
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb4?arch=amd64
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb4?arch=arm64
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb4?arch=armhf
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb4?arch=i386
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb4?arch=ppc64el
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb4?arch=riscv64
- pkg:deb/debian/prometheus-exporter-exporter@0.5.0-1%2Bb4?arch=s390x
