- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=armel
- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=i386
- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=mips64el
- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=mipsel
- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=ppc64el
- pkg:deb/debian/prometheus-frr-exporter@1.1.4-2%2Bb5?arch=s390x
- pkg:deb/debian/prometheus-frr-exporter@1.4.0-1%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-frr-exporter@1.4.0-1%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-frr-exporter@1.4.0-1%2Bb5?arch=armel
- pkg:deb/debian/prometheus-frr-exporter@1.4.0-1%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-frr-exporter@1.4.0-1%2Bb5?arch=i386
- pkg:deb/debian/prometheus-frr-exporter@1.4.0-1%2Bb5?arch=ppc64el
- pkg:deb/debian/prometheus-frr-exporter@1.4.0-1%2Bb5?arch=riscv64
- pkg:deb/debian/prometheus-frr-exporter@1.4.0-1%2Bb5?arch=s390x
- pkg:deb/debian/prometheus-frr-exporter@1.8.1-1?arch=amd64
- pkg:deb/debian/prometheus-frr-exporter@1.8.1-1?arch=arm64
- pkg:deb/debian/prometheus-frr-exporter@1.8.1-1?arch=armhf
- pkg:deb/debian/prometheus-frr-exporter@1.8.1-1?arch=i386
- pkg:deb/debian/prometheus-frr-exporter@1.8.1-1?arch=ppc64el
- pkg:deb/debian/prometheus-frr-exporter@1.8.1-1?arch=riscv64
- pkg:deb/debian/prometheus-frr-exporter@1.8.1-1?arch=s390x
