- pkg:deb/debian/cloud-init@20.4.1-2%2Bdeb11u1?arch=all
- pkg:deb/debian/cloud-init@22.4.2-1%2Bdeb12u3?arch=all
- pkg:deb/debian/cloud-init@25.1.4-1?arch=all
- pkg:deb/debian/cloud-init@25.3-2?arch=all
