- pkg:deb/debian/prometheus-haproxy-exporter@0.12.0%2Bds-2%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-haproxy-exporter@0.12.0%2Bds-2%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-haproxy-exporter@0.12.0%2Bds-2%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-haproxy-exporter@0.12.0%2Bds-2%2Bb5?arch=i386
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=amd64
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=arm64
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=armel
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=armhf
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=i386
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=mips64el
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=mipsel
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=ppc64el
- pkg:deb/debian/prometheus-haproxy-exporter@0.14.0-1%2Bb5?arch=s390x
- pkg:deb/debian/prometheus-haproxy-exporter@0.15.0-3?arch=amd64
- pkg:deb/debian/prometheus-haproxy-exporter@0.15.0-3?arch=arm64
- pkg:deb/debian/prometheus-haproxy-exporter@0.15.0-3?arch=armel
- pkg:deb/debian/prometheus-haproxy-exporter@0.15.0-3?arch=armhf
- pkg:deb/debian/prometheus-haproxy-exporter@0.15.0-3?arch=i386
- pkg:deb/debian/prometheus-haproxy-exporter@0.15.0-3?arch=ppc64el
- pkg:deb/debian/prometheus-haproxy-exporter@0.15.0-3?arch=riscv64
- pkg:deb/debian/prometheus-haproxy-exporter@0.15.0-3?arch=s390x
